config/routes.rb
Rails.application.routes.draw do

  root 'ultimatecode#index'

  get 'login', to: redirect('/auth/google_oauth2'), :as => :login
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  put 'documents/edit_doc_name' => 'documents#edit_doc_name'
  get 'documents/:id/add_collaborator' => 'documents#add_collaborator'
  get 'documents/change_doc', to: 'documents#change_doc'
  put 'documents/delete_doc', to: 'documents#delete_doc'
  resources :documents

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :user
  belongs_to :document
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :user
  has_many :collaborations
  has_many :users, :through => :collaboration
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :documents
	has_many :collaborations

	def self.find_or_create_with_omniauth(auth)
		where(:provider => auth.provider, :uid => auth.uid).first_or_initialize.tap do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.first_name = auth.info.first_name
			user.last_name = auth.info.last_name
			user.email = auth.info.email
			# user.picture = auth.info.image
			user.save!
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :get_document_list

  def authenticate
  	redirect_to :login unless logged_in?
  end

  def current_user
  	@current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	current_user != nil
  end

  def get_document_list
    @document_list = Hash.new
    if logged_in?
      user_id = session[:user_id]
      @document_list['Select files'] = ''
      owned_documents = Document.where(user_id: user_id).order(:id)
      owned_documents.each do |doc|
        @document_list[doc.name] = doc.id
      end

      collaborated_documents = Collaboration.where(user_id: user_id).order(:document_id)
      collaborated_documents.each do |c|
        doc = Document.find(c.document_id)
        if doc
          @document_list[doc.name] = doc.id
        end
      end
    end
    return @document_list
  end
end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  protect_from_forgery with: :null_session

  
  def documents_params
    params.require(:document).permit(:name, :owner, :content)

  end

  def index
    @programming_languages = [['Select Lang','c_cpp'], ['C','c_cpp'], ['C++','c_cpp'], ['CSS','css'], ['Go','golang'], ['HAML','haml'], ['HTML','html'], ['Java','java'], ['Javascript','javascript'], ['JSON','json'], ['MySql','mysql'], ['Python','python'], ['Ruby','ruby']]
    @theme = [['Select Theme','ambiance'], ['Ambiance','ambiance'], ['Chaos','chaos'], ['Dracula','dracula'], ['Cobalt','cobalt'], ['Terminal','terminal'], ['Twilight','twilight'], ['Monokai','monokai'], ['Chrome','chrome'], ['Dawn','dawn'], ['Github','github'], ['Xcode','xcode'],]
    @font_size = [['Font Size', 12], ['12', 12], ['14', 14], ['16', 16], ['18', 18], ['20', 20], ['40', 40], ['80', 80]]

    if session[:current_document_id]
      @current_document = Document.find(session[:current_document_id])
    else
      # Get the last document
      @current_document = Document.limit(1).order("id desc")
    end
  end

  def new
    #default: render index
    user_id = session[:user_id]
    count = Document.where(user_id: user_id).size
    current_time = Time.now
    document = Document.create!(:name => user_id.to_s + '_untitled_' + count.to_s,
      :user_id => user_id,
      :content => "",
      :created_at => current_time,
      :updated_at => current_time)
    session[:current_document_id] = document.id
    redirect_to documents_path
  end

  def show
    document ||= Document.find(params[:id])
    if document
      respond_to do |format|
        content = document.content
        if !content
          content = ""
        end
        msg = { :content => content }
        format.json { render json: msg }
        format.html do
          session[:current_document_id] = document.id
          redirect_to documents_path
        end
      end
    end
  end

  def update
    #params['content'] to get content
    document ||= Document.find(params[:id])
    if document
      document.update(content: params['content'], updated_at: Time.now)
      document.save!
    end
    respond_to do |format|
      format.json { head :ok }
    end
  end

  def edit_doc_name
    current_document_id = session[:current_document_id]
    if !current_document_id
      respond_to do |format|
        msg = { :status => "err", :message => "Current Document ID missing."}
        format.json { render json: msg }
      end
      return
    end

    document = Document.find(current_document_id)
    if document
      document_with_same_name = Document.find_by(name: params['new_doc_name'])
        if document_with_same_name && document_with_same_name.id != current_document_id
          respond_to do |format|
            msg = { :status => "err", :message => "There is an existing file with the same name."}
            format.json { render json: msg }
          end
        else
            document.update(name: params['new_doc_name'], updated_at: Time.now)
            document.save!
            respond_to do |format|
              msg = { :status => "ok", :message => "Success."}
              format.json { render json: msg }
            end
        end
    end
  end

  def add_collaborator
    user = User.find_by_email(params[:email])
    document ||= Document.find(params[:id])
    if user
      document.collaborations.create!(:user_id => user.id)
    end
    respond_to do |format|
      format.json { head :ok }
    end
  end

  def change_doc
    doc = Document.find_by(name: params['file_name'])
    if doc
      session[:current_document_id] = doc.id
        respond_to do |format|
            content = doc.content
            if !content
              content = ""
            end
            msg = { :status => "ok", :content => content }
            format.json { render json: msg }
        end
    else
        respond_to do |format|
            msg = { :status => "err", :message => "file not exist!"}
            format.json { render json: msg }
        end
    end
  end

  def delete_doc
    current_document_id = session[:current_document_id]
    doc = Document.find(current_document_id)
    if doc
        session[:current_document_id] = -1
        file_name = doc.name
        doc.destroy
        respond_to do |format|
            if !file_name
              file_name = ""
            end
            msg = { :status => "ok", :file_name => file_name }
            format.json { render json: msg }
        end
    else
        respond_to do |format|
            msg = { :status => "err", :message => "file not exist!"}
            format.json { render json: msg }
        end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		@user = User.find_or_create_with_omniauth(request.env['omniauth.auth'])
		session[:user_id] = @user.id
		@document_list = [['Select File', '']]
    		document = Document.where(user_id: session[:user_id]).order(:name)
    		document.each do |doc|
        		@document_list.append([doc.name, doc.id])
		end
		redirect_to root_path
	end

	def destroy
		session.delete(:user_id)
		flash[:notice] = 'Logged out successfully.'
		redirect_to root_path
	end
end

app/controllers/ultimatecode_controller.rb
class UltimatecodeController < ApplicationController
  def index
  	#default: render index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collaborations_helper.rb
module CollaborationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/documents/index.html.haml
%html
  %head    
    %div{class:"p2_title"} 

      %span{class:"document_name"}
        %label{:for => "document_name_input", id: "label"} 
          %i{class:"fas fa-file-alt", id:"file_icon"}
        %input#document_name_input{:onblur => "updateDocumentName()", :name => "document_name", :type => "text"} 
        = select_tag :p_style, options_for_select(get_document_list, :selected => @current_document.id), :id => "current-document-selector"
        %span{:id => "delete"}
          %i{class: "fas fa-trash"}
      
      = select_tag :p_font, options_for_select(@font_size), :id => "selector4"
      = select_tag :pl, options_for_select(@programming_languages), :id => "selector3"
      = select_tag :p_style, options_for_select(@theme), :id => "selector2"
      %label{class:"switch"}
        %input{type:"checkbox", id:"switch"}
        %span{class:"slider"} 
          %span{class:"word"} Off &nbsp;On

      %span{:id => "invite"}
        %i{class: "fas fa-plus"} 
        %span Invite

    %div{class:"modal", id: "inviteModal"} 
      %div{class:"modal-content"}
        %span{id: "closeModalBtn"}
          &times;
        %p{id:"modal-title"} Invite Collaborators
        %input{id: "collaborator_email", type: "text", class: "text-line"} 
        %p{id:"modal_footer"} Invited:
        %button{class:"button_add button1", id: "collaboratorAddBtn"} Add 
        
    %br       
    %b
    %div{id:"editor"}
    %br
    %br

app/views/documents/new.html.haml
%html
  %head
    %script(src="//code.jquery.com/ui/1.11.1/jquery-ui.min.js")
    %script(src="//code.jquery.com/jquery-1.11.1.min.js")
    %link(href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css"  rel="stylesheet")
    
   
    %div{class:"p2_title"} 

      %span{class:"doc_name"}
        %label{:for => "docment_name", id: "label"} 
          %i{class:"fas fa-file-alt", id:"file_icon"}
        %input#docment_name_input{:onblur => "updateDocName()", :name => "docment_name", :type => "text"} 
        = select_tag :p_style, options_for_select(@document_list, :selected => @doc_name), :id => "selector5"
      
      = select_tag :p_font, options_for_select(@font_size), :id => "selector4"
      = select_tag :pl, options_for_select(@programming_languages), :id => "selector3"
      = select_tag :p_style, options_for_select(@theme), :id => "selector2"
      %label{class:"switch"}
        %input{type:"checkbox", id:"switch"}
        %span{class:"slider"} 
          %span{class:"word"} Off &nbsp;On
      = hidden_field_tag 'doc_name', @doc_name
    %div{class:"modal", id: "myModal"} 
      %div{class:"modal-content"} 
        %span{class: "close"}
          &times;
        %p{id:"modal_title"} Invite Collaborators
        %input{type: "text", class: "text-line"} 
        %p{id:"modal_footer"} Invited: 
        %button{class:"button_add button1"} Add 
        
    %br       
    %b
    %div{id:"editor"}
    %br
    %br

app/views/documents/update.html.haml
= select_tag :pl, options_for_select(@programming_languages)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %link(rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous")
    %link(href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet")

    %script(src="//cdnjs.cloudflare.com/ajax/libs/ace/1.4.7/ace.js" type="text/javascript" charset="utf-8")
    %script(src="//cdnjs.cloudflare.com/ajax/libs/ace/1.4.7/ext-language_tools.js" type="text/javascript" charset="utf-8")
    %script(src="https://kit.fontawesome.com/302e178b77.js" crossorigin="anonymous")
    %title UltimateCode!
    = stylesheet_link_tag 'application', 'media' => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    %body
      
      - if logged_in?
        = link_to logout_path do
          %span{class: "navBtn", :id => "signOut"}
            %i{class: "fas fa-lock"} 
            %span Sign out
      
      %div.container  
        %div.navbar.navbar-expand-lg.text-white
        #main
          - if flash[:notice]
            %div.alert.alert-danger
              #notice.message= flash[:notice]
          - elsif flash[:warning]
            %div.alert.alert-danger
              #warning.message= flash[:warning]
      
          = yield
      
      

app/views/ultimatecode/index.html.haml
%div{class:"front", id: "front_page"} 
  %h1.title Ultimate Code 
  - if logged_in?
    = select_tag :h_f_selector, options_for_select(get_document_list), :id => "home_file_selector", :class => "btn"
    = form_tag new_document_path, :id => "new_document", :method => :get do
      = hidden_field_tag :user_id, session[:user_id]
      = submit_tag 'New Document', :class => "btn2"

  - else
    %div{id: "sign_in"} Sign in with your:
    %div{class: "icon"}
      = link_to '/auth/google_oauth2' do
        %i{class:"fab fa-google float", id:"google_icon"}   
      %i{class:"fab fa-facebook float", id:"facebook_icon"}   
      %i{class:"fab fa-github float", id:"github_icon"}